# Generated by Django 3.2.9 on 2021-11-20 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('color', models.CharField(default='#FFFFFF', max_length=16)),
                ('title', models.CharField(max_length=20)),
                ('type', models.IntegerField()),
                ('booking_id', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='calendar_date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CheckInOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_childrens', models.IntegerField()),
                ('num_adults', models.IntegerField()),
                ('num_pets', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cleaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('color', models.CharField(default='#FFFFFF', max_length=16)),
                ('assignment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seazone_api.assignment')),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seazone_api.calendar_date'),
        ),
    ]
